# Generated by Django 2.2 on 2019-05-05 05:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='breadth',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='ethnicStudies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='genEd',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
        ),
        migrations.AddField(
            model_name='course',
            name='lasCredit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='prereq',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='course',
            name='typicallyOffered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=[], size=None),
        ),
    ]
