# Generated by Django 2.2 on 2019-05-07 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0003_auto_20190505_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=15000),
        ),
    ]
