# Generated by Django 2.2 on 2019-09-10 19:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0004_auto_20190507_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='difficulty_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2019, 9, 10, 14, 19, 34, 769923)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='interest_rating',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.CharField(default='Teacher', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='success_tips_text',
            field=models.CharField(default='Try hard', max_length=5000),
            preserve_default=False,
        ),
    ]
