# Generated by Django 2.2 on 2019-04-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0005_auto_20190425_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
    ]
