# Generated by Django 2.2 on 2019-04-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_reviews', '0006_remove_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='', max_length=500),
        ),
    ]
